---
title: "Data Description Figure"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    toc: true
knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, output_dir = "C:/Projects/ForecastEvaluation/HTML", encoding = encoding) })
urlcolor: blue
linkcolor: red
---

```{r global_options, echo=FALSE}
knitr::opts_chunk$set(warning=FALSE, echo=TRUE, tidy=TRUE, tidy.opts=list(width.cutoff=60))
```

------------------------------------------------------------------------
```{r libraries, results='hide', warning=FALSE, message=FALSE, echo = FALSE}
library(dplyr)
library(tidyr)
library(purrr)

library(hubUtils)
library(hubEnsembles)
library(hubData)
library(lubridate)
library(ggplot2)
```

```{r, warning = FALSE, message = FALSE}
hub_path <- "C:/Projects/flu-metrocast"
hub_con <- connect_hub(hub_path)


model_by_date <- hub_con %>%
  select(reference_date, model_id) %>%
  distinct() %>%
  collect() %>%
  arrange(reference_date, model_id)

model_by_date

model_order <- c(
  "UT-GBQR", 
  "epiforecasts-dyngam",
  "NAU-Copycat",
  "UMass-alloy",
  "NAU-INFLAenza",
  "UMass-SAR",
  "VTSanghani-PRIME",
  "MOBS-EpyStrain_Flu",
  "ACCIDDA-InfluPaint",
  "epiENGAGE-baseline",
  "epiENGAGE-ensemble_mean",
  "epiENGAGE-lop_norm",
  "FluSight-ensemble" 
)
```

```{r}
plot_df <- model_by_date %>%
  filter(reference_date >= "2025-10-01",
         model_id != "epiENGAGE-GBQR") %>%
  mutate(
    model_id = factor(model_id, levels = rev(model_order)),
    completeness = case_when(
      model_id == "NAU-INFLAenza" & reference_date == as.Date("2025-12-20") ~ "Both",
      model_id %in% c("UT-GBQR", "epiENGAGE-GBQR", "epiENGAGE-baseline", 
                      "epiENGAGE-ensemble_mean", "epiENGAGE-lop_norm") & 
        reference_date == as.Date("2025-11-22") ~ "NC",
      TRUE ~ "Complete"
    )
  )

plot_df <- plot_df %>%
  mutate(completeness = factor(completeness, 
                               levels = c("NC", "SC", "Both", "Complete")))
```
Missing prediction data from NAU-INFLAenza model on the date 12/20/25 for the locations of south-carolina and north-carolina. Additionally, there is missing predictions from the models UT-GBQR, epiENGAGE-GBQR, epiENGAGE-baseline, epiENGAGE-ensemble_mean, and epiENGAGE-lop_norm on the date 11/22/25 for location north-carolina. 
```{r}
# png("Data/data_details.png", 
#       width = 8, height = 4, units = "in", res = 600)
ggplot(plot_df, aes(x = reference_date, y = model_id)) +
  geom_line(aes(group = model_id),
            linewidth = 0.7,
            color = "grey70") +
  geom_point(aes(color = completeness), size = 2) +
  scale_color_manual(
    values = c(
      "NC" = "firebrick",
      "SC" = "royalblue",
      "Both" = "purple",
      "Complete" = "grey40"
    ),
    labels = c(
      "NC" = "NC Missing",
      "SC" = "SC Missing",
      "Both" = "NC + SC Missing",
      "Complete" = "Complete"
    ),
    name = "Prediction completeness"
  ) +
  theme_bw() +
  theme(legend.position = "bottom",
        axis.text.x = element_text(angle = 45, hjust = 1, size = 8)) +
  labs(x = "",
       y = "") +
  scale_x_date(
    breaks = sort(unique(model_by_date$reference_date)),
    date_labels = "%b %d"
  )
```