---
title: "Figure 1"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    toc: true
knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, output_dir = "C:/Projects/ForecastEvaluation/HTML", encoding = encoding) })
urlcolor: blue
linkcolor: red
---

```{r global_options, echo=FALSE}
knitr::opts_chunk$set(fig.height=4, fig.width=6, fig.align = "left", warning=FALSE, echo=TRUE, tidy=TRUE, tidy.opts=list(width.cutoff=60))
```

------------------------------------------------------------------------
```{r libraries, results='hide', warning=FALSE, message=FALSE, echo = FALSE}
library(dplyr)
library(tidyverse)
library(ggplot2)
library(lubridate)
library(patchwork)
library(kableExtra)

library(scoringutils)
library(hubUtils)
library(hubEnsembles)
library(hubData)
```

# Data
```{r}
state_coverage <- read.csv("C:/Projects/ForecastEvaluation/Data/state-scoring/state_coverage.csv")
# state_coverage_summary <- read.csv("C:/Projects/ForecastEvaluation/Data/state-scoring/state_coverage_summary.csv")
state_wis <- read.csv("C:/Projects/ForecastEvaluation/Data/state-scoring/state_wis.csv")
# state_wis_summary <- read.csv("C:/Projects/ForecastEvaluation/Data/state-scoring/state_wis_summary.csv")

standard_coverage <- read.csv("C:/Projects/ForecastEvaluation/Data/standard-scoring/standard_coverage.csv")
# standard_coverage_summary <- read.csv("C:/Projects/ForecastEvaluation/Data/standard-scoring/standard_coverage_summary.csv")
standard_wis <- read.csv("C:/Projects/ForecastEvaluation/Data/standard-scoring/standard_wis.csv")
# standard_wis_summary <- read.csv("C:/Projects/ForecastEvaluation/Data/standard-scoring/standard_wis_summary.csv")
```

# Subfigures
```{r}
model_ids <- c("ACCIDDA-InfluPaint", "MOBS-EpyStrain_Flu", "NAU-Copycat", "NAU-INFLAenza", "UMass-SAR", "UMass-alloy", "UT-GBQR", "VTSanghani-PRIME", "epiENGAGE-baseline", "epiENGAGE-ensemble_mean", "epiENGAGE-lop_norm", "epiforecasts-dyngam")
```

## Figure 1a
```{r}
temp1a_state = state_wis |> group_by(model_id, target) |>  summarise(mean_wis = mean(wis), count = n(), .groups = 'drop')
temp1a_state$type = "state-scoring"

temp1a_standard = standard_wis |> group_by(model_id, target) |>  summarise(mean_wis = mean(wis), count = n(), .groups = 'drop')
temp1a_standard$type = "standard-scoring"

temp1a = rbind(temp1a_standard, temp1a_state)
temp1a = temp1a |> filter(target == "Flu ED visits pct") |> filter(model_id != "epiENGAGE-GBQR") |> filter(model_id != "FluSight-ensemble")

temp1a$model_id <- factor(temp1a$model_id,
  levels = model_ids)
```

```{r}
knitr::kable(temp1a)
```

```{r}
figure1a = ggplot(temp1a, aes(x = model_id, y = mean_wis, fill = type)) + 
  geom_col(position = "dodge", color = "black") + 
  scale_fill_manual(values = c("standard-scoring" = "firebrick", "state-scoring" = "royalblue")) +
  scale_y_continuous(expand = expansion(mult = 0, add = 0.03)) +
  labs(x = "Model", y = "Mean WIS", fill = "Scoring Method") + 
  theme_bw() + theme_bw() +
  theme(
    text = element_text(size = 18),
    axis.text.x = element_text(size = 16, angle = 45, hjust = 1, vjust = 1),
    axis.text.y = element_text(size = 16),
    axis.title = element_text(size = 18),
    legend.text = element_text(size = 16),
    legend.title = element_text(size = 17),
    strip.text = element_text(size = 17)  
  ) +
  theme(legend.position = "top") 

figure1a
```

### Location version 
```{r}
temp1a_state = state_wis |> filter(target == "Flu ED visits pct") |> filter(model_id != "epiENGAGE-GBQR") |> filter(model_id != "FluSight-ensemble") |> group_by(location, target) |>  summarise(mean_wis = mean(wis), count = n(), .groups = 'drop')
temp1a_state$type = "state-scoring"

temp1a_standard = standard_wis |> filter(target == "Flu ED visits pct") |> filter(model_id != "epiENGAGE-GBQR") |> filter(model_id != "FluSight-ensemble") |> group_by(location, target) |>  summarise(mean_wis = mean(wis), count = n(), .groups = 'drop')
temp1a_standard$type = "standard-scoring"

temp1a = rbind(temp1a_standard, temp1a_state)
```

```{r}
knitr::kable(temp1a)
```

```{r, fig.height = 10, fig.width = 10}
figure1a_loc = ggplot(temp1a, aes(x = location, y = mean_wis, fill = type)) + 
  geom_col(position = "dodge", color = "black") + 
  scale_fill_manual(values = c("standard-scoring" = "firebrick", "state-scoring" = "royalblue")) +
  scale_y_continuous(limits = c(0, 2.5), breaks = c(0.5, 1, 1.5, 2, 2.5, 3),
                     expand = expansion(mult = 0, add = 0.03)) +
  labs(x = "Model", y = "Mean WIS", fill = "Scoring Method") + 
  theme_bw() + theme_bw() +
  theme(
    text = element_text(size = 18),
    axis.text.x = element_text(size = 16, angle = 45, hjust = 1, vjust = 1),
    axis.text.y = element_text(size = 16),
    axis.title = element_text(size = 18),
    legend.text = element_text(size = 16),
    legend.title = element_text(size = 17),
    strip.text = element_text(size = 17)  
  ) +
  theme(legend.position = "top") 

figure1a_loc
```

## Figure 1b
### Version 1
```{r}
state_wis_grouped <- state_wis %>%
  group_by(model_id, location, target) %>%
  summarise(state_wis = mean(wis), count = n(), .groups = 'drop')

standard_wis_grouped <- standard_wis %>%
  group_by(model_id, location, target) %>%
  summarise(standard_wis = mean(wis), count = n(), .groups = 'drop')

rWIS_location_target <- standard_wis_grouped %>%
  left_join(state_wis_grouped, 
            by = c("model_id", "location", "target")) %>%
  mutate(mean_relative_wis = state_wis / standard_wis) %>%
  filter(!is.infinite(mean_relative_wis), !is.na(mean_relative_wis))

temp1b <- rWIS_location_target %>%
  filter(target == "Flu ED visits pct") %>%
  filter(model_id != "epiENGAGE-GBQR") %>%
  filter(model_id != "FluSight-ensemble") %>%
  mutate(model_id = factor(model_id, levels = model_ids))
```

```{r}
knitr::kable(temp1b)
```

```{r, fig.height = 10, fig.width = 10}
figure1b_loc = ggplot(temp1b, aes(x = model_id, y = location, fill = mean_relative_wis)) + 
  scale_fill_gradient2(
    low = "green",
    mid = "#ffff00",
    high = "#d32f2f",
    midpoint = 1,
    limits = c(0, 4),   
    name = "Mean Relative WIS"
  ) +
  geom_tile(col = "black") + 
  # geom_text(aes(label = round(mean_relative_wis, 2)), size = 3, color = "black") +
  labs(x = "Model", y = "Location", fill = "Mean Relative WIS") + 
  theme_bw() + 
  theme(legend.position = "top") + 
  theme(
    legend.position = "top",
    text = element_text(size = 14),
    axis.text.x = element_text(size = 11, angle = 45, hjust = 1, vjust = 1),
    axis.text.y = element_text(size = 10),
    axis.title = element_text(size = 14),
    legend.text = element_text(size = 12),
    legend.title = element_text(size = 13),
    strip.text = element_text(size = 12)  
  ) 
figure1b_loc
```

### Version 2
```{r}
state_wis_grouped <- state_wis %>%
  group_by(model_id, target_end_date, target) %>%
  summarise(state_wis = mean(wis), count = n(), .groups = 'drop')

standard_wis_grouped <- standard_wis %>%
  group_by(model_id, target_end_date, target) %>%
  summarise(standard_wis = mean(wis), count = n(), .groups = 'drop')

rWIS_location_target <- standard_wis_grouped %>%
  left_join(state_wis_grouped, 
            by = c("model_id", "target_end_date", "target")) %>%
  mutate(mean_relative_wis = state_wis / standard_wis) %>%
  filter(!is.infinite(mean_relative_wis), !is.na(mean_relative_wis))

temp1b <- rWIS_location_target %>%
  filter(target == "Flu ED visits pct") %>%
  filter(model_id != "epiENGAGE-GBQR") %>%
  filter(model_id != "FluSight-ensemble") %>%
  mutate(model_id = factor(model_id, levels = model_ids))
```

```{r}
knitr::kable(temp1b)
```

```{r, fig.height = 10, fig.width = 10}
figure1b_date = ggplot(temp1b, aes(x = model_id, y = target_end_date, fill = mean_relative_wis)) + 
  scale_fill_gradient2(
    low = "green",
    mid = "#ffff00",
    high = "#d32f2f",
    midpoint = 1,
    limits = c(0, 4),   
    name = "Mean Relative WIS"
  ) +
  geom_tile(col = "black") + 
  geom_text(aes(label = round(mean_relative_wis, 2)), size = 3, color = "black") +
  labs(x = "Model", y = "Date", fill = "Mean Relative WIS") + 
  theme_bw() + 
  theme(legend.position = "top") + 
  theme(
    legend.position = "top",
    text = element_text(size = 14),
    axis.text.x = element_text(size = 11, angle = 45, hjust = 1, vjust = 1),
    axis.text.y = element_text(size = 10),
    axis.title = element_text(size = 14),
    legend.text = element_text(size = 12),
    legend.title = element_text(size = 13),
    strip.text = element_text(size = 12)  
  ) 
figure1b_date
```

## Bottom left
```{r}
state_wis <- read.csv("C:/Projects/ForecastEvaluation/Data/state-scoring/state_wis.csv")
state_wis = state_wis |> rename(state_wis = wis)

complete_wis <- state_wis %>%
  left_join(standard_wis, by = intersect(colnames(state_wis), colnames(standard_wis)))

complete_wis$relative_wis <- complete_wis$state_wis / complete_wis$wis
complete_wis = complete_wis |> select("location", "target_end_date", "horizon", "reference_date",  "model_id", "target", "wis",  "state_wis",    "relative_wis")

complete_wis <- complete_wis %>%
  filter(wis > 0)
```

```{r}
sum(is.na(complete_wis)) 
# complete_wis = na.omit(complete_wis)
```

```{r}
complete_wis_summary <- complete_wis %>%
  group_by(model_id) %>%
  summarise(
    mean_relative_wis = mean(relative_wis[!is.infinite(relative_wis)]),
    count = n(),
    .groups = 'drop'
  )
temp1c = complete_wis_summary |> filter(model_id != "epiENGAGE-GBQR") |> filter(model_id != "FluSight-ensemble")

temp1c$model_id <- factor(temp1c$model_id,
  levels = model_ids)
```

```{r}
knitr::kable(temp1c)
```

```{r}
figure1c = ggplot(temp1c, aes(x = model_id, y = mean_relative_wis)) + 
  geom_col(fill = "firebrick", color = "black") + 
  scale_y_continuous(expand = expansion(mult = 0, add = 0.03)) +
  labs(x = "Model", y = "Mean Relative WIS") + 
   theme_bw() +
  theme(
    text = element_text(size = 18),
    axis.text.x = element_text(size = 16, angle = 45, hjust = 1, vjust = 1),
    axis.text.y = element_text(size = 16),
    axis.title = element_text(size = 18),
    legend.text = element_text(size = 16),
    legend.title = element_text(size = 17),
    strip.text = element_text(size = 17)  
  ) +
  theme(legend.position = "top") + geom_hline(aes(yintercept = 1), col = "black", linetype = "dashed", linewidth = 1.2)

figure1c
```
```{r}
png("Figures/figure1_model_alt.png", width = 1080, height = 720)
figure1c
dev.off()
```

### Location version
```{r}
state_wis <- read.csv("C:/Projects/ForecastEvaluation/Data/state-scoring/state_wis.csv")
state_wis = state_wis |> rename(state_wis = wis)

complete_wis <- state_wis %>%
  left_join(standard_wis, by = intersect(colnames(state_wis), colnames(standard_wis)))

complete_wis$relative_wis <- complete_wis$state_wis / complete_wis$wis
complete_wis = complete_wis |> select("location", "target_end_date", "horizon", "reference_date",  "model_id", "target", "wis",  "state_wis",    "relative_wis")

complete_wis <- complete_wis %>%
  filter(wis > 0)
```

```{r}
sum(is.na(complete_wis)) 
complete_wis = na.omit(complete_wis)
```

```{r}
complete_wis_summary <- complete_wis |> filter(model_id != "epiENGAGE-GBQR") |> filter(model_id != "FluSight-ensemble") %>%
  group_by(location) %>%
  summarise(
    mean_relative_wis = mean(relative_wis[!is.infinite(relative_wis)]),
    count = n(),
    .groups = 'drop'
  )
```

```{r}
temp1c = complete_wis_summary 

lookup = read.csv("data/lookup.csv")
temp1c = temp1c |> left_join(lookup, by = "location") 

temp1c = temp1c |>
  arrange(desc(state), mean_relative_wis) |>
  mutate(location = factor(location, levels = location))
```

```{r}
knitr::kable(temp1c)
```

```{r, fig.height=6, fig.width=14}
figure1c_loc = ggplot(temp1c, aes(x = location, y = mean_relative_wis, fill = state)) + 
  geom_col(color = "black") + 
  scale_y_continuous(expand = expansion(mult = 0, add = 0.03)) +
  labs(x = "Location", y = "Mean Relative WIS") + 
   theme_bw() +
  theme(
    text = element_text(size = 18),
    axis.text.x = element_text(size = 16, angle = 45, hjust = 1, vjust = 1),
    axis.text.y = element_text(size = 16),
    axis.title = element_text(size = 18),
    legend.text = element_text(size = 16),
    legend.title = element_text(size = 17),
    strip.text = element_text(size = 17)  
  ) +
  theme(legend.position = "top") + geom_hline(aes(yintercept = 1), col = "black", linetype = "dashed", linewidth = 1.2)

figure1c_loc
```
```{r}
png("Figures/figure1_loc_alt.png", width = 1080, height = 720)
figure1c_loc
dev.off()
```

### Observed vs predicted version
#### Local
```{r}
raw = read.csv("Data/raw_data.csv")
```

```{r, fig.width=10, fig.height=10}
plot_data <- raw %>%
  filter(output_type == "quantile") %>%
  mutate(
    output_type_id = as.numeric(output_type_id),
    date = as.Date(target_end_date)
  ) %>%
  pivot_wider(
    names_from = output_type_id,
    values_from = value,
    names_prefix = "q_"
  ) %>%
  rename(
    observed = oracle_value,
    predicted_value = `q_0.5`,  
    lower = `q_0.025`,           
    upper = `q_0.975`            
  ) |> filter(model_id == "epiENGAGE-ensemble_mean") |> filter(horizon == 0) |> 
  filter(location %in% c("austin", "san-antonio",  "el-paso", "baltimore", "denver", "portland")) 

plot_data$location = factor(plot_data$location, levels = c("austin", "san-antonio",  
                                                                       "el-paso", "baltimore", "denver", "portland"))
```

```{r, fig.width=20, fig.height=10}
obsvspred_loc <- ggplot(plot_data, aes(x = date)) +
  geom_ribbon(aes(ymin = lower, ymax = upper, fill = "Prediction Interval"),
              alpha = 0.4, color = NA) +
  geom_line(aes(y = predicted_value, color = "Predicted HSA"),
            linewidth = 1) +
  geom_point(aes(y = observed, color = "Observed HSA"),
             size = 2, shape = 16) +
  facet_wrap(~location, nrow=1) +
  scale_color_manual(
    name = NULL,
    values = c(
      "Observed HSA" = "#E74C3C",
      "Predicted HSA" = "#F39C12"
    )
  ) +
  scale_fill_manual(
    name = NULL,
    values = c("Prediction Interval" = "#F39C12")
  ) +
  labs(
    x = NULL,
    y = "Percent Influenza ED Visits"
  ) +
  theme_bw() +
  theme(
    text = element_text(size = 18),
    axis.text.x = element_text(size = 16),
    axis.text.y = element_text(size = 16),
    axis.title = element_text(size = 18),
    legend.text = element_text(size = 16),
    legend.title = element_text(size = 17),
    legend.position = "bottom",
    strip.text = element_text(size = 17)  
  ) + scale_x_date(date_breaks = "2 months", date_labels = "%b") 
 
obsvspred_loc
```

#### State
```{r}
raw_state = read.csv("Data/state_raw.csv")
```

```{r, fig.width=10, fig.height=10}
plot_data_state <- raw_state %>%
  filter(output_type == "quantile") %>%
  mutate(
    output_type_id = as.numeric(output_type_id),
    date = as.Date(target_end_date)
  ) %>%
  pivot_wider(
    names_from = output_type_id,
    values_from = state_value,
    names_prefix = "q_"
  ) %>%
  rename(
    observed = oracle_value,
    predicted_value = `q_0.5`,  
    lower = `q_0.025`,           
    upper = `q_0.975`            
  ) |> filter(model_id == "epiENGAGE-ensemble_mean") |> filter(horizon == 0) |> 
  filter(location %in% c("austin", "san-antonio",  "el-paso", "baltimore", "denver", "portland")) 

plot_data_state$location = factor(plot_data_state$location, levels = c("austin", "san-antonio",  
                                                                       "el-paso", "baltimore", "denver", "portland"))
```

```{r, fig.width=20, fig.height=10}
obsvspred_state <- ggplot(plot_data_state, aes(x = date)) +
  geom_ribbon(aes(ymin = lower, ymax = upper, fill = "Prediction Interval"),
              alpha = 0.4, color = NA) +
  geom_line(aes(y = predicted_value, color = "Predicted HSA"),
            linewidth = 1) +
  geom_point(aes(y = observed, color = "Observed HSA"),
             size = 2, shape = 16) +
  facet_wrap(~location, nrow=1) +
  scale_color_manual(
    name = NULL,
    values = c(
      "Observed HSA" = "#E74C3C",
      "Predicted HSA" = "black"
    )
  ) +
  scale_fill_manual(
    name = NULL,
    values = c("Prediction Interval" = "darkgray")
  ) +
  labs(
    x = NULL,
    y = "Percent Influenza ED Visits"
  ) +
  theme_bw() +
  theme(
    text = element_text(size = 18),
    axis.text.x = element_text(size = 16),
    axis.text.y = element_text(size = 16),
    axis.title = element_text(size = 18),
    legend.text = element_text(size = 16),
    legend.title = element_text(size = 17),
    legend.position = "bottom",
    strip.text = element_text(size = 17)  
  ) + scale_x_date(date_breaks = "2 months", date_labels = "%b") 
 
obsvspred_state
```

```{r, fig.width=20, fig.height=15}
fig1c_timeseries = obsvspred_loc / obsvspred_state
fig1c_timeseries
```

## Bottom right
```{r}
temp1d_state = state_coverage |> group_by(model_id, target) |>  
  summarise(mean_coverage = mean(coverage_95), count = n(), .groups = 'drop')
temp1d_state$type = "state-scoring"

temp1d_standard = standard_coverage |> group_by(model_id, target) |> 
  summarise(mean_coverage = mean(coverage_95), count = n(), .groups = 'drop')
temp1d_standard$type = "standard-scoring"

temp1d = rbind(temp1d_standard, temp1d_state)
temp1d = temp1d |> filter(target == "Flu ED visits pct") |> filter(model_id != "epiENGAGE-GBQR") |> filter(model_id != "FluSight-ensemble")

temp1d$model_id <- factor(temp1d$model_id,
  levels = model_ids)
```

```{r}
knitr::kable(temp1d)
```

```{r}
figure1d = ggplot(temp1d, aes(x = model_id, y = mean_coverage, fill = type)) + 
  geom_col(col = "black", position = "dodge") + 
  scale_fill_manual(values = c("standard-scoring" = "firebrick", "state-scoring" = "royalblue")) +
  labs(x = "Model", y = "Mean Coverage (95%)", fill = "Scoring Method") + 
  theme_bw() + 
  theme(legend.position = "top") + 
  theme(
    text = element_text(size = 14),
    axis.text.x = element_text(size = 11, angle = 45, hjust = 1, vjust = 1),
    axis.text.y = element_text(size = 10),
    axis.title = element_text(size = 14),
    legend.text = element_text(size = 12),
    legend.title = element_text(size = 13),
    strip.text = element_text(size = 12)  
  ) + scale_y_continuous(expand = expansion(mult = 0, add = 0.03))

figure1d
```

# Figure 1
```{r, fig.height = 20, fig.width = 20}
(figure1a + figure1d) / ((fig1c_timeseries))
```
## Figure 5 (1.2, overflow)
```{r, fig.height = 20, fig.width = 20}
figure1b_loc + figure1b_date

```

## Save to files
```{r}
png("Figures/figure1.png", width = 1920, height = 1920)
(figure1a + figure1d) / ((fig1c_timeseries))
dev.off()
```

```{r}
png("Figures/figure5.png", width = 1920, height = 1920)
(figure1b_loc + figure1b_date)
dev.off()
```