---
title: "Figure 2"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    toc: true
knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, output_dir = "C:/Projects/ForecastEvaluation/HTML", encoding = encoding) })
urlcolor: blue
linkcolor: red
---

```{r global_options, echo=FALSE}
knitr::opts_chunk$set(fig.height=4, fig.width=6, fig.align = "left", warning=FALSE, echo=TRUE, tidy=TRUE, tidy.opts=list(width.cutoff=60))
```

------------------------------------------------------------------------
```{r libraries, results='hide', warning=FALSE, message=FALSE, echo = FALSE}
library(dplyr)
library(gratia)
library(tidyverse)
library(ggplot2)
library(lubridate)
library(patchwork)
library(kableExtra)
library(mgcv)

library(scoringutils)
library(hubUtils)
library(hubEnsembles)
library(hubData)
```

# Data
```{r}
state_wis <- read.csv("C:/Projects/ForecastEvaluation/Data/state-scoring/state_wis.csv")
standard_wis <- read.csv("C:/Projects/ForecastEvaluation/Data/standard-scoring/standard_wis.csv")
state_wis = state_wis |> rename(state_wis = wis)
```

```{r}
complete_wis <- state_wis %>%
  left_join(standard_wis, by = intersect(colnames(state_wis), colnames(standard_wis)))

# complete_wis$relative_wis <- complete_wis$state_wis / complete_wis$wis
complete_wis = complete_wis |> select("location", "target_end_date", "horizon", "reference_date",  "model_id", "target", "wis",  "state_wis")

# complete_wis <- complete_wis %>%
  # filter(wis > 0)
```

# NA stuff
Since I removed relative_wis and the wis cutoff of 0, I essentially added 47 new entries (in a dataset of 58000) which might slightly affect the models. Mainly VTSanghani which had 46 out of the 47 with state_wis and wis = 0.
```{r}
sum(is.na(complete_wis$wis))
na <- complete_wis %>%
  filter(if_any(everything(), is.na))

table(na$location)
table(na$target_end_date)
table(na$model_id)
```

```{r}
# complete_wis = na.omit(complete_wis)
standard_wis$horizon = (as.character(standard_wis$horizon))

complete_wis$model_id <- droplevels(as.factor(complete_wis$model_id))
complete_wis$horizon <- droplevels(as.factor(complete_wis$horizon))
complete_wis$location <- droplevels(as.factor(complete_wis$location))

complete_wis = complete_wis |> filter(target == "Flu ED visits pct",
         !model_id %in% c("epiENGAGE-GBQR", "ACCIDDA-InfluPaint", "MOBS-EpyStrain_Flu"),
         model_id != "FluSight-ensemble") 

complete_wis_filtered <- complete_wis %>%
  filter(wis > 0, state_wis > 0) |> # Not sure we should be doing this -- if there are scores that are 0, we should just use a Tweedie distribution?
  rename(wis = wis_local, wis_state = state_wis) |> 
  pivot_longer(
      c(state_wis, wis),
      names_to = "geo_granularity",
      values_to = "all_wis", 
      names_prefix = "wis_"
    ) |>
  mutate(local = ifelse(geo_granularity == "local", TRUE, FALSE))
```


# Model effects
```{r}
# This model now includes on the as an outcome variable all WIS scores (we should discuss if these are log-transformed or natural) and on the RHS an indicator variable for whether that WIS is from a local model (local = TRUE) or whether it is from a state model applied to local data (local = FALSE). 
model <- gam(
  all_wis ~  local + 
             s(model_id, bs = "re") +
             s(location, bs = "re") +
             s(horizon, k = 4), # optional
             s(model_id, bs = "re", by = local) + # additional effect for local
             s(location, bs = "re", by = local) +
             s(horizon, k = 4, by = local),
  family = Gamma(link = "log"),
  data = complete_wis_filtered,  
  method = "REML"
)

# This means that exp(beta_local) is the average multipliative effect of being a local model (>1 means it worsens performance, <1 means it improves performance). The intercept is the average score.
# And the the location/model/horizon random effects tell you the additional multiplicative effect of location/model/horizon have specifically on the local model's performance, on top of the avergae local effect capture by beta_local.
summary(model)
```

```{r, fig.height = 6, fig.width = 6}
par(mfrow = c(2, 2))
gam.check(model)
par(mfrow = c(1, 1))
```

```{r}
estimates <- smooth_estimates(model)

make_ci_table <- function(smooth_name, group_var) {
  estimates |>
    filter(.smooth == smooth_name) |>
    select(.smooth, {{ group_var }}, .estimate, .se) |>
    rename(est = .estimate, se = .se) |>
    mutate(
      ci_lower = est - 1.96 * se,
      ci_upper = est + 1.96 * se,
      pct_est   = (exp(est) - 1) * 100,
      pct_lower = (exp(ci_lower) - 1) * 100,
      pct_upper = (exp(ci_upper) - 1) * 100,
      excludes_zero = ci_lower > 0 | ci_upper < 0
    ) |>
    arrange(est)
}

model_id_ci  <- make_ci_table("s(model_id)", model_id)
location_ci  <- make_ci_table("s(location)", location)
horizon_ci   <- make_ci_table("s(horizon)", horizon)

knitr::kable(model_id_ci |> select(-.smooth))
knitr::kable(location_ci |> select(-.smooth))
knitr::kable(horizon_ci |> select(-.smooth))

```

# Figure 2
```{r, fig.height=20, fig.width=20}
fig2a <- ggplot(model_id_ci, aes(x = reorder(model_id, -pct_est), y = pct_est)) +
  geom_errorbar(aes(ymin = pct_lower, ymax = pct_upper), width = 0.2) +
  geom_point(color = "seagreen", size = 5) + 
  geom_hline(yintercept = 0, linetype = "dashed", linewidth = 1) +
  labs(y = "Random effect (% diff on WIS)", x = "Model") +
  theme_bw() + 
  coord_flip() + 
  theme(
    text            = element_text(size = 27),
    axis.text.x     = element_text(size = 24),
    axis.text.y     = element_text(size = 24),
    axis.title      = element_text(size = 27),
    legend.text     = element_text(size = 24),
    legend.title    = element_text(size = 25.5),
    strip.text      = element_text(size = 25.5)
  ) + scale_x_discrete(labels = function(x) gsub("-", "-\n", x))
```

```{r, fig.height=20, fig.width=20}
fig2b <- ggplot(horizon_ci, aes(x = reorder(horizon, -pct_est), y = pct_est)) +
  geom_errorbar(aes(ymin = pct_lower, ymax = pct_upper), width = 0.2) +
  geom_point(color = "coral", size = 5) + 
  geom_hline(yintercept = 0, linetype = "dashed", linewidth = 1) +
  labs(y = "Random effect (% diff on WIS)", x = "Horizon") +
  theme_bw() + 
  coord_flip() + 
  theme(
    text            = element_text(size = 27),
    axis.text.x     = element_text(size = 24),
    axis.text.y     = element_text(size = 24),
    axis.title      = element_text(size = 27),
    legend.text     = element_text(size = 24),
    legend.title    = element_text(size = 25.5),
    strip.text      = element_text(size = 25.5)
  )
```

```{r}
lookup = read.csv("Data/lookup.csv")
location_ci = location_ci |> left_join(lookup, by = "location")
```

```{r}
state_order = location_ci |>
  distinct(location, state, pct_est) |>
  arrange(state, desc(pct_est))

location_ci = location_ci |>
  mutate(location = factor(location, levels = state_order$location))

state_boundaries = which(diff(as.numeric(factor(state_order$state, 
                                                 levels = unique(state_order$state)))) != 0) + 0.5

fig2c <- ggplot(location_ci, aes(x = location, y = pct_est, color = state)) + 
  geom_vline(xintercept = state_boundaries, color = "black", linewidth = 1.0) +
  geom_errorbar(aes(ymin = pct_lower, ymax = pct_upper), width = 0.2) +
  geom_point(size = 5) + 
  geom_hline(yintercept = 0, linetype = "dashed", linewidth = 1) +
  labs(y = "Random effect (% diff on WIS)", x = "Location") +
  theme_bw() + 
  coord_flip() + 
  theme(
    text            = element_text(size = 27),
    axis.text.x     = element_text(size = 24),
    axis.text.y     = element_text(size = 24),
    axis.title      = element_text(size = 27),
    legend.text     = element_text(size = 24),
    legend.title    = element_text(size = 25.5),
    strip.text      = element_text(size = 25.5)
  ) 
```

```{r, fig.height=15, fig.width=20}
fig2_left = (fig2a / fig2b)
((fig2_left) | plot_spacer() | (fig2c)) + plot_layout(ncol = 3, widths = c(0.35, 0.05, 0.55))
```

```{r, fig.height = 10, fig.width = 15}
(fig2a | fig2b)

```

```{r}
png("Figures/figure2.png", width = 1920, height = 1440)
((fig2_left) | plot_spacer() | (fig2c)) + plot_layout(ncol = 3, widths = c(0.35, 0.05, 0.55))
dev.off()
```

