---
title: "Figure 3"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    toc: true
knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, output_dir = "C:/Projects/ForecastEvaluation/HTML", encoding = encoding) })
urlcolor: blue
linkcolor: red
---

```{r global_options, echo=FALSE}
knitr::opts_chunk$set(fig.height=4, fig.width=6, fig.align = "left", warning=FALSE, echo=TRUE, tidy=TRUE, tidy.opts=list(width.cutoff=60))
```

------------------------------------------------------------------------
```{r libraries, results='hide', warning=FALSE, message=FALSE, echo = FALSE}
library(dplyr)
library(tidyverse)
library(ggplot2)
library(lubridate)
library(patchwork)
library(kableExtra)

library(scoringutils)
library(hubUtils)
library(hubEnsembles)
library(hubData)
```

# Data
```{r}
standard_coverage <- read.csv("C:/Projects/ForecastEvaluation/Data/standard-scoring/standard_coverage.csv")
# standard_coverage_summary <- read.csv("C:/Projects/ForecastEvaluation/Data/standard-scoring/standard_coverage_summary.csv")
standard_wis <- read.csv("C:/Projects/ForecastEvaluation/Data/standard-scoring/standard_wis.csv")
# standard_wis_summary <- read.csv("C:/Projects/ForecastEvaluation/Data/standard-scoring/standard_wis_summary.csv")
```

# Subfigures
```{r}
model_ids <- c("UT-GBQR", "epiforecasts-dyngam", "NAU-Copycat", "UMass-alloy",
               "NAU-INFLAenza", "UMass-SAR", "VTSanghani-PRIME",
               "epiENGAGE-baseline", "epiENGAGE-ensemble_mean")
```

## Left
```{r}
standard_coverage <- read.csv("C:/Projects/ForecastEvaluation/Data/standard-scoring/standard_coverage.csv")
standard_coverage <- standard_coverage |> 
  select(location, target_end_date, horizon, reference_date, model_id, target, coverage_95, prediction_category) |>
  mutate(horizon = horizon + 1)

temp3a <- standard_wis %>% 
  left_join(standard_coverage, 
            by = join_by(location, target_end_date, horizon, reference_date, model_id, target)) %>% filter(model_id %in% model_ids)

table(is.na(temp3a$prediction_category))

temp3a$model_id <- factor(temp3a$model_id,
  levels = model_ids)
```

```{r}
plot_df <- temp3a %>%
  group_by(model_id, prediction_category) %>%
  summarise(mean_wis = mean(wis, na.rm = TRUE), .groups = "drop") %>%
  group_by(model_id) %>%
  mutate(total_wis = sum(mean_wis)) %>%
  ungroup()

plot_df$prediction_category <- factor(plot_df$prediction_category, levels = c("over", "on-target", "under"))
```

```{r}
figure3a = ggplot(plot_df, aes(x = model_id, y = mean_wis, fill = prediction_category)) +
  geom_col(col = "black") +
  labs(x = "Model (all horizons)", y = "Mean WIS", fill = "Prediction Category") + theme_bw(base_size = 18)+ theme(
    text = element_text(size = 18),
    axis.text.x = element_text(size = 16, angle = 45, hjust = 1, vjust = 1),
    axis.text.y = element_text(size = 16),
    axis.title = element_text(size = 18),
    legend.text = element_text(size = 16),
    legend.title = element_text(size = 17),
    strip.text = element_text(size = 17),
    legend.position = "top"
  ) 
figure3a
```

## Top right
```{r}
temp3b = standard_coverage |> group_by(model_id, horizon) |> 
  summarise(mean_coverage = mean(coverage_95, na.rm = TRUE), .groups = "drop") %>%
  group_by(model_id) %>%
  ungroup() %>% filter(model_id %in% model_ids)

temp3b$model_id <- factor(temp3b$model_id,
  levels = model_ids)
```

```{r}
figure3b = ggplot(temp3b) + geom_tile(col='black',aes(y=model_id, x=horizon, fill = mean_coverage)) + scale_fill_viridis_c(option = "plasma", direction = -1) + theme_bw(base_size = 18) + labs(x="Horizon (1-4)", y = "Model", fill = "Mean Coverage (95%)") + coord_flip() + theme(
    text = element_text(size = 18),
    axis.text.x = element_text(size = 16, angle = 45, hjust = 1, vjust = 1),
    axis.text.y = element_text(size = 16),
    axis.title = element_text(size = 18),
    legend.text = element_text(size = 16),
    legend.title = element_text(size = 17),
    strip.text = element_text(size = 17), legend.position = "top"
  ) 
figure3b
```


## Bottom right
```{r}
temp3c = standard_wis |>
    group_by(target_end_date, model_id, horizon) |>
    summarize(mean_wis = mean(wis, na.rm = TRUE), .groups = "drop") %>% filter(model_id %in% model_ids)

temp3c$target_end_date = as.Date(temp3c$target_end_date)

temp3c$model_id <- factor(temp3c$model_id,
  levels = model_ids)
```

```{r}
figure3c = ggplot() +
  geom_line(
    data = subset(temp3c, model_id != "epiENGAGE-ensemble_mean"),
    aes(target_end_date, mean_wis, color = model_id), linewidth = 1
  ) +
  geom_line(
    data = subset(temp3c, model_id == "epiENGAGE-ensemble_mean"),
    aes(target_end_date, mean_wis, color = model_id), linewidth = 1.2
  ) +
  scale_color_manual(
    values = c(setNames(scales::hue_pal()(length(unique(temp3c$model_id)) - 1),
                         setdiff(unique(temp3c$model_id), "epiENGAGE-ensemble_mean")),
                "epiENGAGE-ensemble_mean" = "black")
  ) + labs(y = "Mean WIS", x = "Date", color = "Model") +
  scale_x_date(date_breaks = "1 month", date_labels = "%b %Y") + 
  facet_wrap(~horizon,  labeller = labeller(horizon = as_labeller(function(x) paste("Horizon", x)))) + theme_bw() +
  theme(
    text = element_text(size = 18),
    axis.text = element_text(size = 16),
    axis.title = element_text(size = 18),
    legend.text = element_text(size = 16),
    legend.title = element_text(size = 17),
    strip.text = element_text(size = 17),
    legend.position = "bottom"
  )

figure3c
```

# Figure 3
```{r, fig.height = 20, fig.width = 20}
(figure3a + figure3b) / (figure3c)
```

## Save to file
```{r}
png("Figures/figure3.png", width = 1920, height = 1920)
(figure3a + figure3b) / (figure3c)
dev.off()
```